### ISSUE TITLE
pip install specifies 'numba==0.50.1' which conflicts with deeplabcut 2.2rc2 'numba==0.51.1'

### ISSUE THREAD

**Issue by jonmatthis** [lambdaloop/camibrate#8]
I'm trying to create an enviornment that includes both aniposelib and deeplab cut, but I ran into this conflict - 

```
The conflict is caused by:
    aniposelib 0.4.1 depends on numba==0.50.1
    deeplabcut 2.2rc2 depends on numba==0.51.1
``` 

aniposelib runs just fine with numba==0.51.1, but the pip install specifies version 0.50.1

**Comment by jonmatthis** [comment]
On closer inspection - Your requirements.txt file does not specific a version for numba, but the deeplabcut requirements.txt file specifies 0.51.1

**Comment by lambdaloop** [comment]
Our setup.py did specify a specific version of numba==0.50.1 
I removed that requirement as of aniposelib 0.4.2, it should work fine now
